#!/bin/bash
#rm -rf Dockerfile
#rm -rf README.md
rm -rf __pycache__
rm -rf bin
rm -rf chainer
rm -rf chainer-7.0.0.dist-info
rm -rf chainermn
rm -rf chainerx
#rm -rf data.txt
#rm -rf delete.sh
#rm -rf deploy.sh
rm -rf easy_install.py
rm -rf filelock-3.0.12.dist-info
rm -rf filelock.py
rm -rf google
rm -rf h5py
rm -rf h5py-2.10.0.dist-info
#rm -rf lambda_function.py
#rm -rf model.hdf5
#rm -rf model.py
#rm -rf model.vocab
rm -rf numpy
rm -rf numpy-1.18.0.dist-info
rm -rf oji_classification.zip
rm -rf onnx_chainer
rm -rf pkg_resources
rm -rf protobuf-3.11.2-py3.7-nspkg.pth
rm -rf protobuf-3.11.2.dist-info
#rm -rf rcnn-text-classification.iml
#rm -rf requirements.txt
#rm -rf run.sh
rm -rf setuptools
rm -rf setuptools-*.dist-info
rm -rf six-1.13.0.dist-info
rm -rf six.py
rm -rf typing_extensions-3.7.4.1.dist-info
rm -rf typing_extensions.py
rm -rf boto3
rm -rf boto3-*dist-info
rm -rf botocore
rm -rf botocore-*dist-info
rm -rf dateutil
rm -rf python_dateutil-2.8.1.dist-info
rm -rf docutils
rm -rf docutils-0.15.2.dist-info
rm -rf urllib3
rm -rf urllib3-*.dist-info
rm -rf setuptools-45.0.0.dist-info
rm -rf s3transfer
rm -rf s3transfer-*.dist-info
rm -rf jmespath
rm -rf jmespath-*.dist-info